### ISSUE TITLE
Hakuna Livestream links

### ISSUE THREAD

**Issue by geolehmann** [gembelinternet/Hakuna-Project#1]
Hi,

I am working on a project for the app too and wanted to ask if you maybe figured out how to retrieve links like m3u8 or flv for the livestreams.

Thanks in advance!

**Comment by gembelinternet** [comment]
@geolehmann You can use from nodejs package [m3u8 stream reader](https://github.com/fent/node-m3u8stream)

**Comment by geolehmann** [comment]
Hi, thanks for your fast response. I was talking about the actual URLs for a hakuna stream. using the API I can get the list of live rooms, but I did not figure out yet how to get the link of the streams. I did some traffic analysis and didn't see any m3u8 or flv packets,  which makes me wonder if hakuna uses something like webrtc

**Comment by gembelinternet** [comment]
@geolehmann that is using webrtc protocol, try to analyst request and respond from server to capture the flag
